Repository nordtheme/vim, pull requests merged in 2019-04, with the labels that each got.

#151 Improve CMake generator expression highlighting
  colors/nord.vim
Labels: context-syntax-support, type-improvement

#153 Theme config for bolder vertical split line
  README.md
  assets/scrot-config-bold-vertical-split-line-default.png
  assets/scrot-config-bold-vertical-split-line.png
  colors/nord.vim
Labels: context-config-support, context-ui-support, scope-ux, type-feature

#150 Haskell Syntax Plugin Support
  colors/nord.vim
Labels: context-plugin-support, context-syntax-support, scope-compatibility, type-feature

#152 Basic support for Asciidoc syntax highlighting
  colors/nord.vim
Labels: context-syntax-support, scope-compatibility, type-feature

#134 Fix for terminal statusline in airline
  autoload/airline/themes/nord.vim
Labels: context-plugin-support, context-ui-support, scope-compatibility

#135 Add more ALE Highlights
  colors/nord.vim
Labels: context-plugin-support, context-syntax-support, type-improvement

#130 Add support for airline warning and error colors
  autoload/airline/themes/nord.vim
Labels: context-plugin-support, context-ui-support, scope-compatibility, type-feature

#154 Basic syntax highlighting support for Rust
  colors/nord.vim
Labels: context-syntax-support, scope-compatibility, type-feature

#140 changes of IncSearch color so that were difference from Search color
  colors/nord.vim
Labels: context-ui-support, scope-ux, status-pending, status-requires-revision, type-improvement
