Repository nordtheme/vim, pull requests merged in 2021-05, with the labels that each got.

#224 Add public API function to get Nord colors
  colors/nord.vim
Labels: context-api, scope-dx, status-pending, status-requires-revision, type-feature

#261 Conceal highlighting group support
  colors/nord.vim
Labels: context-syntax, scope-compatibility, scope-quality, type-feature

#229 Improve highlights for Neovim LSP
  colors/nord.vim
Labels: context-plugin-support, context-ui, scope-compatibility, scope-ux, target-neovim, type-feature

#252 Fix: wrong group name
  colors/nord.vim
Labels: context-ui, scope-quality, status-accepted, type-bug
