Repository nordtheme/vim, pull requests merged in 2022-05, with the labels that each got.

#312 GitHub Flow migration
  CHANGELOG.md
  README.md
  license
Labels: type-improvement, context-docs, context-workflow, scope-compatibility, scope-maintainability, scope-stability, scope-quality

#314 From `master` to `main`
  changelog.md
  readme.md
Labels: context-docs, type-subtask, context-workflow, scope-compatibility, scope-maintainability

#316 Add Gitsigns and Sneak support
  colors/nord.vim
Labels: type-feature, context-ui, context-plugin, scope-compatibility
