Repository nordtheme/vim, pull requests merged in 2022-04, with the labels that each got.

#294 Don't load plugin-related things when the relevant plugin isn't installed
  colors/nord.vim
Labels: type-improvement, scope-performance, scope-compatibility, scope-ux

#297 exist should be exists
  colors/nord.vim
Labels: type-bug, context-plugin, priority-high, scope-stability, scope-ux, scope-quality

#295 Simplify the conditions at the beginning of the theme
  colors/nord.vim
Labels: type-improvement, scope-maintainability, scope-quality

#307 Revert conditional plugin loading
  colors/nord.vim
Labels: type-bug, context-plugin, priority-high, scope-compatibility, scope-ux, scope-quality

#305 Use one more ternary
  colors/nord.vim
Labels: type-improvement, scope-quality

#303 Only call exec once per group
  colors/nord.vim
Labels: type-improvement, scope-performance, scope-quality
