Repository nordtheme/vim, pull requests merged in 2022-01, with the labels that each got.

#282 Add support for neovim 0.6.0 diagnostic API highlight groups
  colors/nord.vim
Labels: context-ui, status-requires-revision, type-task, target-neovim, scope-compatibility

#284 Add support for LSP textDocument/documentHighlight
  colors/nord.vim
Labels: type-feature, context-syntax, target-neovim, scope-compatibility, scope-ux, status-requires-review

#283 Improve readability of C language constants
  colors/nord.vim
Labels: type-improvement, context-syntax, status-requires-revision, scope-compatibility
